name: Sync Google Calendar

on:
  push:
    paths:
      - 'ordini.json'

jobs:
  send-to-calendar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read and send events to Google Calendar
        run: |
          python3 <<EOF
import json
import requests
from datetime import datetime

# Carica file ordini.json
with open("ordini.json", "r", encoding="utf-8") as f:
    data = json.load(f)

tasks = data.get("pianificazione", [])

eventi = []

for giorno in tasks:
    data_g = giorno.get("giorno")
    ambiente = giorno.get("ambiente", "")
    for task in giorno.get("task_list", []):
        start = datetime.strptime(f"{data_g} {task['ora']}", "%Y-%m-%d %H:%M")
        dur = task.get("durata", "00:30")
        h, m = map(int, dur.split(":"))
        end = start.replace(minute=start.minute + m, hour=start.hour + h)
        eventi.append({
            "titolo": task["nome"],
            "inizio": start.isoformat(),
            "fine": end.isoformat(),
            "descrizione": f"Cliente: {task['nome'].split('–')[-1].strip()}"
        })

response = requests.post(
    "https://script.google.com/macros/s/AKfycby9TFzR8zYm1ezmvWZADRf3ntYCCv3jM5kRjIF-D2zJj1t4vZoYHtW6Zm7igV_LEq-ZsA/exec",
    json=eventi
)

print("Risposta dallo script Google:", response.text)
EOF
